AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template IAM Role for SageMaker
Resources:
  DemoDecisionTreeRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
      Path: /
      RoleName: DemoDecisionTreeRole
      Policies:
        - PolicyName: GeneralPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:DeleteProject'
                  - 'codebuild:CreateProject'
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: 'arn:aws:codebuild:*:*:project/sagemaker-studio*'
              - Effect: Allow
                Action: 'logs:CreateLogStream'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/codebuild/sagemaker-studio*'
              - Effect: Allow
                Action:
                  - 'logs:GetLogEvents'
                  - 'logs:PutLogEvents'
                Resource: >-
                  arn:aws:logs:*:*:log-group:/aws/codebuild/sagemaker-studio*:log-stream:*
              - Effect: Allow
                Action: 'logs:CreateLogGroup'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ecr:CreateRepository'
                  - 'ecr:BatchGetImage'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:DescribeImages'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:UploadLayerPart'
                  - 'ecr:ListImages'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:PutImage'
                Resource: 'arn:aws:ecr:*:*:repository/sagemaker-studio*'
              - Effect: Allow
                Action: 'ecr:GetAuthorizationToken'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                  - 's3:PutObject'
                Resource: 'arn:aws:s3:::sagemaker-*/*'
              - Effect: Allow
                Action:
                  - 's3:CreateBucket'
                Resource: 'arn:aws:s3:::sagemaker*'
              - Effect: Allow
                Action:
                  - 'iam:GetRole'
                  - 'iam:ListRoles'
                Resource: '*'
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: 'arn:aws:iam::*:role/*'
                Condition:
                  StringLikeIfExists:
                    'iam:PassedToService': codebuild.amazonaws.com
